:- module(colors, []).

color(dark, blast).
color(green, blast).
color(gray, blast).
color(brown, blast).
color(red, blast).
color(purple, brown_spot).
color(brown, brown_spot).
color(gray, brown_spot).
color(red, brown_spot).
color(gray, sheath_blight).
color(gray, sheath_blight).
color(white, sheath_blight).
color(brown, sheath_blight).
color(yellow, red_stripe).
color(green, red_stripe).
color(orange, red_stripe).
color(yellow, bakanae).
color(green, bakanae).
color(orange, false_smut).
color(green, false_smut).
color(black, false,smut).
color(yellow, rice_grassy_stunt).
color(green, rice_grassy_stunt).
color(orange, tungro).
color(yellow, tungro).
color(light_tan, leaf_scald).
color(dark, leaf_scald).
color(brown, leaf_scald).
color(red, leaf_scald).
color(light, narrow_brown_spot).
color(dark, narrow_brown_spot).
color(brown, narrow_brown_spot).
color(dark, sheath_rot).
color(red, sheath_rot).
color(brown, sheath_rot).
color(gray, sheath_rot).
color(yellow, bacterial_blight).
