:- module(places, []).

place(leaf, blast).
place(collar, blast).
place(node, blast).
place(neck, blast).
place(panicle, blast).
place(leaf_sheath, blast).
place(coleoptile, brown_spot).
place(leaf, brown_spot).
place(leaf_sheath, brown_spot).
place(panicle, brown_spot).
place(glume, brown_spot).
place(spikelet, brown_spot).
place(seed, brown_spot).
place(leaf_sheath, sheath_blight).
place(red_stripe, leaf).
place(root, bakanae).
place(crown, bakanae).
place(spikelet, false_smut).
place(leaf, rice_grassy_stunt).
place(leaf_blade, leaf_scald).
place(leaf, leaf_scald).
place(leaf, narrow_brown_spot).
place(leaf_sheath, narrow_brown_spot).
place(pedicel, narrow_brown_spot).
place(upper_most_leaf_sheath, sheath_rot).
place(leaf, bacterial_blight).
place(seedling, bacterial_blight).
place(leaf_blade, bacterial_blight).
place(leaf_tips, bacterial_blight).
